export const SUCCESS_REQUEST = 200;
export const BAD_REQUEST_ERROR = 400;
export const UNAUTHORIZED_ERROR = 401;
export const ENTITY_DUPLICATION_ERROR = 403;
export const NOT_FOUND_ERROR = 404;
export const INTERNAL_SERVER_ERROR = 500;