export enum Authority {
  CREATE_PRODUCT_REQUISITION = 'CREATE_PRODUCT_REQUISITION',
  READ_PRODUCT_REQUISITION = 'READ_PRODUCT_REQUISITION',
  UPDATE_PRODUCT_REQUISITION = 'UPDATE_PRODUCT_REQUISITION',
  APPROVE_PRODUCT_REQUISITION = 'APPROVE_PRODUCT_REQUISITION',
  READ_USER_APPROVAL = 'READ_USER_APPROVAL',

  // Authority
  READ_AUTHORITY = 'READ_AUTHORITY',
  CREATE_AUTHORITY = 'CREATE_AUTHORITY',

  // Permission
  READ_PERMISSION = 'READ_PERMISSION',
  CREATE_PERMISSION = 'CREATE_PERMISSION',

  // Role
  READ_ROLE = 'READ_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',

  // Employee
  READ_USER = 'READ_USER',

  // UserRole
  CREATE_USER_ROLE = 'CREATE_USER_ROLE',

  CREATE = 'CREATE',
  MANAGE = 'MANAGE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  APPROVE = 'APPROVE'
}
