export enum Authority {
  CREATE_PRODUCT_REQUISITION = 'CREATE_PRODUCT_REQUISITION',
  READ_PRODUCT_REQUISITION = 'READ_PRODUCT_REQUISITION',
  APPROVE_PRODUCT_REQUISITION = 'APPROVE_PRODUCT_REQUISITION'
}
