export type TEnv = {
  broker: string;
  port: number;
  dataSource: {
    hostMySql: string;
    userMySql: string;
    passwordMySql: string;
    databaseMySql: string;
  };
  hashSalt: string;
  jwtSecret: string;
  passportSecret: string;
  duration: number;
  refreshableDuration: number;
  tag: string;
  swaggerEnpoint: string;
};

export * from "./base.type";
export * from "./error-code.type";
export * from "./auth.type";
export * from "./site.type";
export * from "./project.type";
export * from "./unit.type";
export * from "./product.type";
export * from "./company.type";
export * from "./product-requisition-from.type";
export * from "./role.type";
export * from "./authority.type";
export * from "./permission.type";
export * from "./user-role.type";
export * from "./request-product.type";
export * from "./department.type";
export * from "./user-department.type";
export * from "./assigned-user-approval.type";
export * from "./warehouse.type";
export * from "./product-warehouse.type";
export * from "./temporary-product.type";
export * from "./file.type";
export * from "./approval-log.types";
export * from "./user.type";
export * from "./resource.type";
export * from "./role-permission.type";
export * from "./purchase-product.type";
export * from "./product-purchase-form.type";
export * from "./notification.type";
export * from "./producer.type";
