name: Deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
        run: |
          echo "$ENV_PROD" > .deploy/.env

      - name: Deploy with Docker Compose
        env:
          REMOTE_HOST_PROD: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER_PROD: ${{ secrets.REMOTE_USER_PROD }}
          SSH_PORT_PROD: ${{ secrets.SSH_PORT_PROD }}
          SSH_PRIVATE_KEY_PROD: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_PROD" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT_PROD $REMOTE_HOST_PROD >> ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://$REMOTE_USER_PROD@$REMOTE_HOST_PROD:$SSH_PORT_PROD"

          docker ps -a
          docker compose -f .deploy/docker-compose.prod.yaml pull
          docker compose -f .deploy/docker-compose.prod.yaml down
          docker compose -f .deploy/docker-compose.prod.yaml up -d
          docker image prune -f  # clean up none image after built
