name: Deploy

on:
  push:
    tags:
      - "*" # This triggers the workflow on any tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }} # Use your private SSH key from GitHub Secrets

      - name: Set tag as environment variable
        id: set_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy production
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST_PROD }}
          username: ${{ secrets.REMOTE_USER_PROD }}
          port: ${{ secrets.SSH_PORT_PROD }} # Specify your SSH port here
          script: |
            cd cmsweb-v2/  # Change to your application directory on the remote host

            # Update the .env file with the current tag
            echo "TAG=${{ env.TAG }}" >> .deploy/.env

            git pull origin main  # Pull latest changes

            docker compose -f .deploy/docker-compose.prod.yaml down

            docker compose -f .deploy/docker-compose.prod.yaml up -d --build

            docker image prune -f  # clean up none image after built
