name: Deploy

on:
  pull_request_target:
    branches: [ main ]
    types: [opened, closed]
  workflow_run:
    workflows: ["Build and Test"]  # Trigger after 'Build and Test' workflow succeeds
    types:
      - completed

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Remote Host using Docker
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}  # Specify your SSH port here
          script: |
            cd cmsweb-v2/  # Change to your application directory on the remote host
            git pull origin main  # Pull latest changes
            docker compose -f .deploy/docker-compose.dev.yaml down
            docker compose -f .deploy/docker-compose.dev.yaml up -d --build
            docker image prune -f  # clean up none image after built