name: publish-prod

on:
  push:
    tags:
      - "v*" # This triggers the workflow on any tag

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: homeslands

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    environment: development

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          FE_ENV_PROD: ${{ secrets.FE_ENV_PROD }}
        run: |
          echo "$FE_ENV_PROD" > app/frontend/.env

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cmsweb-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/backend
          file: ./.build/backend/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-api:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-api
          push: true

      - name: Build and push cmsweb-ui image
        uses: docker/build-push-action@v4
        with:
          context: ./app/frontend
          file: ./.build/frontend/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-ui:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-ui
          push: true

      - name: Build and push cmsweb-docs image
        uses: docker/build-push-action@v4
        with:
          context: ./docsify
          file: ./.build/docsify/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-docs:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-docs
          push: true

      - name: Build and push cmsweb-notification image
        uses: docker/build-push-action@v4
        with:
          context: ./app/notification-service
          file: ./.build/notification/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-notification:latest
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-notification
          push: true
