name: publish-dev

on:
  pull_request_target:
    branches: [dev]
    types: [opened, closed]
  workflow_run:
    workflows: ["build-and-test"] # Trigger after 'build-and-test' workflow succeeds
    types:
      - completed

env:
  REGISTRY: ghcr.io
  REPOSITORY_OWNER: homeslands

jobs:
  publish-dev:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    environment: development

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (optional for multi-arch support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Copy Environment Configuration
        env:
          FE_ENV_DEV: ${{ secrets.FE_ENV_DEV }}
        run: |
          echo "$FE_ENV_DEV" > app/frontend/.env

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push cmsweb-api image
        uses: docker/build-push-action@v4
        with:
          context: ./app/backend
          file: ./.build/backend/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-api:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-api
          push: true

      - name: Build and push cmsweb-ui image
        uses: docker/build-push-action@v4
        with:
          context: ./app/frontend
          file: ./.build/frontend/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-ui:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-ui
          push: true

      - name: Build and push cmsweb-docs image
        uses: docker/build-push-action@v4
        with:
          context: ./docsify
          file: ./.build/docsify/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-docs:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-docs
          push: true

      - name: Build and push cmsweb-notification image
        uses: docker/build-push-action@v4
        with:
          context: ./app/notification-service
          file: ./.build/notification/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-notification:dev
          labels: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/cmsweb-notification
          push: true

      - name: Pull latest images on remote server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_PRIVATE_KEY_DEV: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY_DEV" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT $REMOTE_HOST >> ~/.ssh/known_hosts
          export DOCKER_HOST="ssh://$REMOTE_USER@$REMOTE_HOST:$SSH_PORT"

          docker compose -f .deploy/docker-compose.dev.yaml pull
